name: Analyze with CodeGuru Reviewer

on: 
 - push
 - workflow_dispatch # This allows manual triggering of the action through the GitHub UI.

permissions:
    id-token: write
    contents: read
    security-events: write 

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      id: iam-role
      continue-on-error: false
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::632161794143:role/OIDCgithub-Role-1TPDCXLLTEOWR
        aws-region: us-west-2
    
    - uses: actions/checkout@v2
      if: steps.iam-role.outcome == 'success'
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      if: steps.iam-role.outcome == 'success'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      if: steps.iam-role.outcome == 'success'
      run: mvn compile -DskipTests

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      if: steps.iam-role.outcome == 'success'
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-githubactions-awsbin
        build_path: ./target/classes
        
    - name: Rename file 
      run: mv codeguru-results.sarif.json codeguru-results.sarif

    - name: Delete file 
      run: rm -f codeguru-results.sarif.json    
    
    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: codeguru-results.sarif
    - name: Run PMD
      id: pmd
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'rulesets/java/quickstart.xml'
        sourcePath: 'src/main/java'
        analyzeModifiedFilesOnly: false
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: pmd-report.sarif        
